# Generated by Django 4.2.2 on 2023-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="food",
            field=models.ManyToManyField(to="django_app.movie"),
        ),
    ]
