# Generated by Django 4.2.2 on 2023-06-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_food"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="food",
            new_name="movie",
        ),
    ]
