# Generated by Django 5.0.8 on 2024-08-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
