# Generated by Django 5.0.8 on 2024-08-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_remove_user_age_remove_user_date_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=20),
        ),
    ]
