# Generated by Django 5.0.8 on 2024-08-08 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="movie",
        ),
    ]
